version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - misspell
    - unparam

formatters:
  enable:
    - gofmt
