version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - misspell
    - unparam
    - forbidigo

  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          pkg: ^internal/.*$
          msg: "Do not use fmt.Print in internal packages; use a logger or return values."
        - pattern: ^os\.Stdout$
          pkg: ^internal/.*$
          msg: "Do not use os.Stdout in internal packages."
  exclusions:
    rules:
      - path: "cmd/.*"
        linters:
          - forbidigo

formatters:
  enable:
    - gofmt
