import { Adapter, CompiledFile } from '../adapters';
import { UniversalAgentDefinition } from '../types';

export const geminiCliAdapter: Adapter = {
  id: 'gemini-cli',
  name: 'Gemini CLI',
  description: 'Compiles to GEMINI.md.',
  compile: (def: UniversalAgentDefinition) => {
    const warnings: string[] = [];
    const files: CompiledFile[] = [];
    
    // GEMINI.md structure usually allows importing other files or just flat context.
    // We'll flatten for now, but respect scopes.
    
    const parts: string[] = [];

    // Optional header
    parts.push('# Project Instructions (Generated by MarkDowntown)');

    for (const block of def.blocks) {
      const targetScopes = block.scopes && block.scopes.length > 0 ? block.scopes : ['root'];
      
      for (const scope of targetScopes) {
        if (scope === 'root' || scope === '.' || scope === '/' || scope === '') {
          parts.push(block.content);
        } else {
           parts.push(`### Scope: ${scope}\n\n${block.content}`);
        }
      }
    }

    files.push({
      path: 'GEMINI.md',
      content: parts.join('\n\n---\n\n'),
    });

    return { files, warnings };
  }
};
